# https://hub.docker.com/_/mysql
# Use root/example as user/password credentials
version: '3.6'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init/db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reminder
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "127.0.0.1:3307:3306"
  mockServer:
    image: mockserver/mockserver:5.13.2
    ports:
      - 9090:1080
    environment:
#      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: ./init/mockserver
        target: /config